"""empty message

Revision ID: 249e665afbf2
Revises: 159a9ab6519c
Create Date: 2022-01-20 23:01:50.370179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249e665afbf2'
down_revision = '159a9ab6519c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=120), nullable=True),
    sa.Column('michrochip', sa.String(length=120), nullable=True),
    sa.Column('found_date', sa.String(length=120), nullable=True),
    sa.Column('injured', sa.String(length=120), nullable=True),
    sa.Column('possible_name', sa.String(length=120), nullable=True),
    sa.Column('color', sa.String(length=120), nullable=False),
    sa.Column('size', sa.String(length=120), nullable=True),
    sa.Column('weight', sa.String(length=120), nullable=True),
    sa.Column('picture', sa.String(length=120), nullable=True),
    sa.Column('zipcode', sa.String(length=120), nullable=False),
    sa.Column('post_creator', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('michrochip'),
    sa.UniqueConstraint('post_creator')
    )
    op.add_column('user', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('zipcode', sa.String(length=120), nullable=False))
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'zipcode')
    op.drop_column('user', 'name')
    op.drop_table('pet')
    # ### end Alembic commands ###
