"""empty message

Revision ID: 54d980028a01
Revises: 
Create Date: 2022-02-21 18:52:43.481830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d980028a01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('zipcode', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('possible_name', sa.String(length=120), nullable=True),
    sa.Column('gender', sa.String(length=120), nullable=True),
    sa.Column('michrochip', sa.String(length=120), nullable=True),
    sa.Column('found_date', sa.String(length=120), nullable=True),
    sa.Column('injured', sa.String(length=120), nullable=True),
    sa.Column('color', sa.String(length=120), nullable=False),
    sa.Column('size', sa.String(length=120), nullable=True),
    sa.Column('weight', sa.String(length=120), nullable=True),
    sa.Column('picture', sa.String(length=120), nullable=True),
    sa.Column('zipcode', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet')
    op.drop_table('user')
    # ### end Alembic commands ###
