"""empty message

Revision ID: 7a357fd2431a
Revises: f61ce40908b3
Create Date: 2022-02-05 17:11:28.746452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a357fd2431a'
down_revision = 'f61ce40908b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('possible_name', sa.String(length=120), nullable=True))
    op.add_column('pet', sa.Column('zipcode', sa.String(length=120), nullable=False))
    op.drop_column('pet', 'name')
    op.drop_column('pet', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('location', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('pet', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('pet', 'zipcode')
    op.drop_column('pet', 'possible_name')
    # ### end Alembic commands ###
