"""empty message

Revision ID: a573503e6e63
Revises: 6e466eec7947
Create Date: 2022-01-29 15:59:58.989145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a573503e6e63'
down_revision = '6e466eec7947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('name', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet', 'name')
    # ### end Alembic commands ###
