"""empty message

Revision ID: a645a5218103
Revises: 249e665afbf2
Create Date: 2022-01-29 21:22:08.108436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a645a5218103'
down_revision = '249e665afbf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('pet', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('pet_post_creator_key', 'pet', type_='unique')
    op.create_foreign_key(None, 'pet', 'user', ['user_id'], ['id'])
    op.drop_column('pet', 'post_creator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('post_creator', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pet', type_='foreignkey')
    op.create_unique_constraint('pet_post_creator_key', 'pet', ['post_creator'])
    op.drop_column('pet', 'user_id')
    op.drop_column('pet', 'name')
    # ### end Alembic commands ###
