"""empty message

Revision ID: f19f6506c16a
Revises: 3bad25952e71
Create Date: 2022-02-05 17:15:08.267539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19f6506c16a'
down_revision = '3bad25952e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pet_michrochip_key', 'pet', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('pet_michrochip_key', 'pet', ['michrochip'])
    # ### end Alembic commands ###
