"""empty message

Revision ID: f61ce40908b3
Revises: 3bad25952e71
Create Date: 2022-02-05 14:37:00.155019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f61ce40908b3'
down_revision = '3bad25952e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('pet', sa.Column('location', sa.String(length=120), nullable=False))
    op.drop_column('pet', 'zipcode')
    op.drop_column('pet', 'possible_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('possible_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('pet', sa.Column('zipcode', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('pet', 'location')
    op.drop_column('pet', 'name')
    # ### end Alembic commands ###
